; generated by Component: ARM Compiler 5.06 update 6 (build 750) Tool: ArmCC [4d3637]
; commandline ArmCC [--c99 --split_sections --debug -c --asm --gnu -o.\objects\fsl_gpio.o --depend=.\objects\fsl_gpio.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\board -I..\..\CMSIS\Include -I..\..\devices\MK66F18 -I..\..\devices\MK66F18\drivers -I..\..\devices\MK66F18\arm -I..\..\devices\MK66F18\utilities -I..\..\devices\MK66F18\utilities\str -I..\..\devices\MK66F18\utilities\debug_console -I..\..\TestingFiles -I..\..\SpiCommunication -I..\..\I2Commands -I..\..\HelpingModules -I..\k66 -I..\..\components\serial_manager -I..\..\spiApp -I..\..\application -I.\RTE\_Target_1 -I"C:\Users\Taraz Tech1\AppData\Local\Arm\Packs\Keil\Kinetis_K60_DFP\1.5.0\Device\Include" -IC:\Keil_v5\ARM\CMSIS\Include -D__UVISION_VERSION=528 -DMK66FN2M0xxx18 -DCPU_MK66FN2M0VLQ18 --omf_browse=.\objects\fsl_gpio.crf ..\..\devices\MK66F18\drivers\fsl_gpio.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.GPIO_GetInstance||, CODE, READONLY, ALIGN=2

GPIO_GetInstance PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOVS     r4,#0
        B        |L1.22|
|L1.8|
        LDR      r0,|L1.48|
        LDR      r0,[r0,r4,LSL #2]
        CMP      r0,r5
        BNE      |L1.20|
        B        |L1.26|
|L1.20|
        ADDS     r4,r4,#1
|L1.22|
        CMP      r4,#5
        BCC      |L1.8|
|L1.26|
        NOP      
        CMP      r4,#5
        BCS      |L1.34|
        B        |L1.44|
|L1.34|
        MOVS     r2,#0x43
        ADR      r1,|L1.52|
        ADR      r0,|L1.96|
        BL       __aeabi_assert
|L1.44|
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP

|L1.48|
        DCD      s_gpioBases
|L1.52|
        DCB      "..\\..\\devices\\MK66F18\\drivers\\fsl_gpio.c",0
        DCB      0
        DCB      0
        DCB      0
|L1.96|
        DCB      "instance < ARRAY_SIZE(s_gpioBases)",0
        DCB      0

        AREA ||i.GPIO_PinInit||, CODE, READONLY, ALIGN=2

GPIO_PinInit PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        CBZ      r6,|L2.14|
        B        |L2.24|
|L2.14|
        MOVS     r2,#0x64
        ADR      r1,|L2.80|
        ADR      r0,|L2.124|
        BL       __aeabi_assert
|L2.24|
        MOVS     r7,#1
        LDRB     r0,[r6,#0]
        CBNZ     r0,|L2.42|
        LDR      r0,[r4,#0x14]
        LSL      r1,r7,r5
        BICS     r0,r0,r1
        STR      r0,[r4,#0x14]
        B        |L2.76|
|L2.42|
        MOV      r0,r5
        LDRB     r1,[r6,#1]
        MOVS     r2,#1
        CBNZ     r1,|L2.58|
        LSL      r3,r2,r0
        STR      r3,[r4,#8]
        B        |L2.64|
|L2.58|
        LSL      r3,r2,r0
        STR      r3,[r4,#4]
|L2.64|
        NOP      
        LDR      r0,[r4,#0x14]
        LSL      r1,r7,r5
        ORRS     r0,r0,r1
        STR      r0,[r4,#0x14]
|L2.76|
        POP      {r4-r8,pc}
        ENDP

|L2.80|
        DCB      "..\\..\\devices\\MK66F18\\drivers\\fsl_gpio.c",0
        DCB      0
        DCB      0
        DCB      0
|L2.124|
        DCB      "NULL != config",0
        DCB      0

        AREA ||i.GPIO_PortClearInterruptFlags||, CODE, READONLY, ALIGN=2

GPIO_PortClearInterruptFlags PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r4,r1
        MOV      r0,r5
        BL       GPIO_GetInstance
        UXTB     r6,r0
        LDR      r0,|L3.32|
        LDR      r7,[r0,r6,LSL #2]
        STR      r4,[r7,#0xa0]
        POP      {r4-r8,pc}
        ENDP

        DCW      0x0000
|L3.32|
        DCD      s_portBases

        AREA ||i.GPIO_PortGetInterruptFlags||, CODE, READONLY, ALIGN=2

GPIO_PortGetInterruptFlags PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r0,r4
        BL       GPIO_GetInstance
        UXTB     r5,r0
        LDR      r0,|L4.24|
        LDR      r6,[r0,r5,LSL #2]
        LDR      r0,[r6,#0xa0]
        POP      {r4-r6,pc}
        ENDP

|L4.24|
        DCD      s_portBases

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.constdata||, DATA, READONLY, ALIGN=2

s_portBases
        DCD      0x40049000
        DCD      0x4004a000
        DCD      0x4004b000
        DCD      0x4004c000
        DCD      0x4004d000
s_gpioBases
        DCD      0x400ff000
        DCD      0x400ff040
        DCD      0x400ff080
        DCD      0x400ff0c0
        DCD      0x400ff100

;*** Start embedded assembler ***

#line 1 "..\\..\\devices\\MK66F18\\drivers\\fsl_gpio.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___10_fsl_gpio_c_c53caebd____REV16|
#line 468 "..\\..\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___10_fsl_gpio_c_c53caebd____REV16| PROC
#line 469

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___10_fsl_gpio_c_c53caebd____REVSH|
#line 483
|__asm___10_fsl_gpio_c_c53caebd____REVSH| PROC
#line 484

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___10_fsl_gpio_c_c53caebd____RRX|
#line 670
|__asm___10_fsl_gpio_c_c53caebd____RRX| PROC
#line 671

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT GPIO_PinInit [CODE]
        EXPORT GPIO_PortClearInterruptFlags [CODE]
        EXPORT GPIO_PortGetInterruptFlags [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_assert [CODE]

        KEEP GPIO_GetInstance
        KEEP s_portBases
        KEEP s_gpioBases

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
